version: '3'
services:
  db:
    image: postgres:11.2-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: >-
      bash -c "rm -rf /myapp/baukis2/tmp/pids/*.pid && bundle install -j4 &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      WEBPACKER_DEV_SERVER_HOST: "0.0.0.0"
      RAILS_SERVE_STATIC_FILES: "1"
      EDITOR: "vim"
    volumes:
      - ./apps/baukis2:/myapp/baukis2
    working_dir: /myapp/baukis2
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    stdin_open: true
    tty: true
